# Here, all the parameters configurations are added
base:
  project: Insurance-premium-prediction
  random_state: 42
  target_col: expenses

data_source:
  s3_source: data_given/insurance.csv

load_data:
  raw_dataset: data/raw/insurance.csv

split_data:
  train_path: data/processed/train_insurance.csv
  test_path: data/processed/test_insurance.csv
  test_size: 0.2

estimators:
  

model_dir: saved_models

